### ISSUE TITLE
Allow saving and loading of appointments

### ISSUE THREAD

**Issue by muruges95** [CS2103JAN2018-W14-B4/main#14]
Need to modify storage component to allow storage of the added appointments, and also make it such that the program will read the appointments when starting up to populate the calendar.

**Comment by tzerbin** [comment]
Appointment to store Title:String, Interval (Start Time, End Time):String, FullDayFlag:boolean, CalendarName:String, Location:String

**Comment by tzerbin** [comment]
Refer to PR #53
