### ISSUE TITLE
Create Tests for addAppointment Feature

### ISSUE THREAD

**Issue by WJY-norainu** [CS2103JAN2018-W14-B4/main#36]
Tasks include:
Implement AddAppointmentCommandTest class
Implement AddAppointmentCommandParserTest class
Implement AddAppointmentCommandSystemTest class
Make change to AddressBookParserTest class and other relevant files if applicable to cover different aspects of the tests

**Comment by muruges95** [comment]
Finished Creating AddAppointmentCommandParserTest #45

**Comment by muruges95** [comment]
Just left with the system test.
